clone:
  depth: 1

image:
  name: benquike/ubuntu20.04:gcc_clang
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
  run-as-user: 1000

pipelines:
  default:
    - step:
        name: Checkout Submodules & Edit and Build Test-Suite
        script:
          - echo $BITBUCKET_CLONE_DIR
          - cd $BITBUCKET_CLONE_DIR
          - git submodule init
          - git submodule update
          - cd Test-Suite
          - sed -i 's|/vfs_tests/|/fs_tests/|g' CMakeLists.txt
          - ./generate_bc.sh

    - step:
        name: Prepare build directory
        script:
          - cd $BITBUCKET_CLONE_DIR
          - cmake -E make_directory Debug-build
          - cd Debug-build
          - cmake -DSVF_BUILD_UNITTESTS=On -DCMAKE_BUILD_TYPE=Debug ..

    - step:
        name: Check code format
        script:
          - cd $BITBUCKET_CLONE_DIR
          - cmake --build Debug-build --target check-format

    - step:
        name: Build source code
        script:
          - cd $BITBUCKET_CLONE_DIR
          - cd Debug-build
          - cmake --build . --config Debug -j

    - step:
        name: Run unittest
        script:
          - cd $BITBUCKET_CLONE_DIR
          - cd Debug-build
          - ctest
