clone:
  depth: 1

image:
  name: benquike/ubuntu20.04:gcc_clang
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
  run-as-user: 1000

pipelines:
  default:
    - step:
        name: Checkout Submodules & Check code format & Build & Test
        script:
          - git submodule init
          - git submodule update
          - cd Test-Suite
          - sed -i 's|/vfs_tests/|/fs_tests/|g' CMakeLists.txt
          - ./generate_bc.sh; cd ..
          - cmake -E make_directory Debug-build
          - cd Debug-build
          - cmake -DSVF_BUILD_UNITTESTS=On -DCMAKE_BUILD_TYPE=Debug ..; cd ..
          - cmake --build Debug-build --target check-format # check code format
          - cmake --build . --config Debug -j # build the code
          - ctest # run ctest
