/// Automatically genenerated by ./gen_serialization_exports.py
/// Date & time: 04/17/2021 22:27:32
/// Note: do not include this file directly

#ifndef __UTIL_BOOST_CLASSES_EXPORT_H__
#define __UTIL_BOOST_CLASSES_EXPORT_H__
// ICFG Edges
BOOST_CLASS_EXPORT(SVF::GenericICFGEdgeTy)
BOOST_CLASS_EXPORT(SVF::ICFGEdge)
BOOST_CLASS_EXPORT(SVF::IntraCFGEdge)
BOOST_CLASS_EXPORT(SVF::CallCFGEdge)
BOOST_CLASS_EXPORT(SVF::RetCFGEdge)
// ICFG Graphs
BOOST_CLASS_EXPORT(SVF::GenericICFGTy)
BOOST_CLASS_EXPORT(SVF::ICFG)
// ICFG Nodes
BOOST_CLASS_EXPORT(SVF::GenericICFGNodeTy)
BOOST_CLASS_EXPORT(SVF::ICFGNode)
BOOST_CLASS_EXPORT(SVF::GlobalBlockNode)
BOOST_CLASS_EXPORT(SVF::IntraBlockNode)
BOOST_CLASS_EXPORT(SVF::InterBlockNode)
BOOST_CLASS_EXPORT(SVF::FunEntryBlockNode)
BOOST_CLASS_EXPORT(SVF::FunExitBlockNode)
BOOST_CLASS_EXPORT(SVF::CallBlockNode)
BOOST_CLASS_EXPORT(SVF::RetBlockNode)
// PAG Edges
BOOST_CLASS_EXPORT(SVF::GenericPAGEdgeTy)
BOOST_CLASS_EXPORT(SVF::PAGEdge)
BOOST_CLASS_EXPORT(SVF::AddrPE)
BOOST_CLASS_EXPORT(SVF::CopyPE)
BOOST_CLASS_EXPORT(SVF::CmpPE)
BOOST_CLASS_EXPORT(SVF::BinaryOPPE)
BOOST_CLASS_EXPORT(SVF::UnaryOPPE)
BOOST_CLASS_EXPORT(SVF::StorePE)
BOOST_CLASS_EXPORT(SVF::LoadPE)
BOOST_CLASS_EXPORT(SVF::GepPE)
BOOST_CLASS_EXPORT(SVF::NormalGepPE)
BOOST_CLASS_EXPORT(SVF::VariantGepPE)
BOOST_CLASS_EXPORT(SVF::CallPE)
BOOST_CLASS_EXPORT(SVF::RetPE)
BOOST_CLASS_EXPORT(SVF::TDForkPE)
BOOST_CLASS_EXPORT(SVF::TDJoinPE)
// PAG Graphs
BOOST_CLASS_EXPORT(SVF::GenericPAGTy)
BOOST_CLASS_EXPORT(SVF::PAG)
// PAG Nodes
BOOST_CLASS_EXPORT(SVF::GenericPAGNodeTy)
BOOST_CLASS_EXPORT(SVF::PAGNode)
BOOST_CLASS_EXPORT(SVF::ValPN)
BOOST_CLASS_EXPORT(SVF::ObjPN)
BOOST_CLASS_EXPORT(SVF::GepValPN)
BOOST_CLASS_EXPORT(SVF::FIObjPN)
BOOST_CLASS_EXPORT(SVF::RetPN)
BOOST_CLASS_EXPORT(SVF::VarArgPN)
BOOST_CLASS_EXPORT(SVF::DummyValPN)
BOOST_CLASS_EXPORT(SVF::DummyObjPN)
BOOST_CLASS_EXPORT(SVF::CloneDummyObjPN)
BOOST_CLASS_EXPORT(SVF::CloneGepObjPN)
BOOST_CLASS_EXPORT(SVF::CloneFIObjPN)
// PTA Callgraph Edges
BOOST_CLASS_EXPORT(SVF::GenericCallGraphEdgeTy)
BOOST_CLASS_EXPORT(SVF::PTACallGraphEdge)
// PTA Callgraph Nodes
BOOST_CLASS_EXPORT(SVF::GenericCallGraphNodeTy)
BOOST_CLASS_EXPORT(SVF::PTACallGraphNode)
// PTA Callgraphs
BOOST_CLASS_EXPORT(SVF::GenericCallGraphTy)
BOOST_CLASS_EXPORT(SVF::PTACallGraph)
// SVFG
BOOST_CLASS_EXPORT(SVF::SVFG)
// SVFG Edges
BOOST_CLASS_EXPORT(SVF::IndirectSVFGEdge)
BOOST_CLASS_EXPORT(SVF::IntraIndSVFGEdge)
BOOST_CLASS_EXPORT(SVF::CallIndSVFGEdge)
BOOST_CLASS_EXPORT(SVF::RetIndSVFGEdge)
BOOST_CLASS_EXPORT(SVF::ThreadMHPIndSVFGEdge)
// SVFG Nodes
BOOST_CLASS_EXPORT(SVF::MRSVFGNode)
BOOST_CLASS_EXPORT(SVF::FormalINSVFGNode)
BOOST_CLASS_EXPORT(SVF::FormalOUTSVFGNode)
BOOST_CLASS_EXPORT(SVF::ActualINSVFGNode)
BOOST_CLASS_EXPORT(SVF::ActualOUTSVFGNode)
BOOST_CLASS_EXPORT(SVF::MSSAPHISVFGNode)
BOOST_CLASS_EXPORT(SVF::IntraMSSAPHISVFGNode)
BOOST_CLASS_EXPORT(SVF::InterMSSAPHISVFGNode)
// SVFGOPT
BOOST_CLASS_EXPORT(SVF::SVFGOPT)
// VFG Edges
BOOST_CLASS_EXPORT(SVF::VFGEdge)
BOOST_CLASS_EXPORT(SVF::DirectSVFGEdge)
BOOST_CLASS_EXPORT(SVF::IntraDirSVFGEdge)
BOOST_CLASS_EXPORT(SVF::CallDirSVFGEdge)
BOOST_CLASS_EXPORT(SVF::RetDirSVFGEdge)
// VFG Nodes
BOOST_CLASS_EXPORT(SVF::GenericVFGNodeTy)
BOOST_CLASS_EXPORT(SVF::VFGNode)
BOOST_CLASS_EXPORT(SVF::StmtVFGNode)
BOOST_CLASS_EXPORT(SVF::LoadVFGNode)
BOOST_CLASS_EXPORT(SVF::StoreVFGNode)
BOOST_CLASS_EXPORT(SVF::CopyVFGNode)
BOOST_CLASS_EXPORT(SVF::CmpVFGNode)
BOOST_CLASS_EXPORT(SVF::BinaryOPVFGNode)
BOOST_CLASS_EXPORT(SVF::UnaryOPVFGNode)
BOOST_CLASS_EXPORT(SVF::GepVFGNode)
BOOST_CLASS_EXPORT(SVF::PHIVFGNode)
BOOST_CLASS_EXPORT(SVF::IntraPHIVFGNode)
BOOST_CLASS_EXPORT(SVF::AddrVFGNode)
BOOST_CLASS_EXPORT(SVF::ArgumentVFGNode)
BOOST_CLASS_EXPORT(SVF::ActualParmVFGNode)
BOOST_CLASS_EXPORT(SVF::FormalParmVFGNode)
BOOST_CLASS_EXPORT(SVF::ActualRetVFGNode)
BOOST_CLASS_EXPORT(SVF::FormalRetVFGNode)
BOOST_CLASS_EXPORT(SVF::InterPHIVFGNode)
BOOST_CLASS_EXPORT(SVF::NullPtrVFGNode)
// VFGS
BOOST_CLASS_EXPORT(SVF::VFG)
#endif
