name: CMake build and test (Debug build + ASAN)

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  BUILD_DIR: Debug-build

jobs:
  build:

    # The CMake configure and build commands are platform
    # agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a
    # matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install and Setup clang/llvm
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./scripts/setup_github_ci_container.sh

    - name: Update Test-Suite CMakeLists.txt and Build Test-Suite
      working-directory: ${{github.workspace}}/Test-Suite
      shell: bash
      run: sed -i 's|/vfs_tests/|/fs_tests/|g' CMakeLists.txt; ./generate_bc.sh

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/$BUILD_DIR

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSVF_BUILD_UNITTESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address -g" -DCMAKE_C_FLAGS="-fsanitize=address -g" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address"

    - name: Build
      working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: ctest
      working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # run: make test SvfUnitTests
      run: ASAN_OPTIONS=new_delete_type_mismatch=0 ctest

    - name: unittests
      working-directory: ${{github.workspace}}/${{env.BUILD_DIR}}
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # run: make test SvfUnitTests
      run: ASAN_OPTIONS=new_delete_type_mismatch=0 LSAN_OPTIONS=suppressions=../scripts/MyLSAN.supp ../scripts/find_and_execute_unittests.sh
